name: scancode-toolkit
base: core24
version: v32.3.3
summary: ScanCode toolkit
description: |
  ScanCode detects licenses, copyrights, dependencies by "scanning code" ... to
  discover and inventory open source and third-party packages used in your code.
license: Apache-2.0

source-code: https://github.com/alexmurray/scancode-toolkit-snap.git
issues: https://github.com/alexmurray/scancode-toolkit-snap/issues

grade: stable
confinement: strict

apps:
  scancode:
    command: bin/snapcraft-preload $SNAP/scancode
    environment:
      LC_ALL: C
    plugs:
      - home
  extractcode:
    command: bin/snapcraft-preload $SNAP/extractcode
    environment:
      LC_ALL: C
    plugs:
      - home
  license-data:
    command: bin/snapcraft-preload $SNAP/venv/bin/scancode-license-data
    environment:
      LC_ALL: C
    plugs:
      - home

parts:
  scancode-toolkit:
    plugin: dump
    source: https://github.com/aboutcode-org/scancode-toolkit/releases/download/$SNAPCRAFT_PROJECT_VERSION/scancode-toolkit-$SNAPCRAFT_PROJECT_VERSION_py3.12-linux.tar.gz
    build-packages:
      - libxml2-dev
      - libxslt1-dev
      - python3
      - wget
    stage-packages:
      - libgomp1
      - libxml2
      - libxslt1.1
      - python3
    override-build: |
      snapcraftctl build
      # configure venv etc
      $SNAPCRAFT_PART_BUILD/configure
      for f in $(grep -l $SNAPCRAFT_PART_BUILD $SNAPCRAFT_PART_BUILD/venv/bin/*); do sed -i "s|$SNAPCRAFT_PART_BUILD|/snap/scancode-toolkit/current|" $f; done
      cp -a $SNAPCRAFT_PART_BUILD/venv $SNAPCRAFT_PART_INSTALL

  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/
    build-packages:
      - on amd64:
          - gcc-multilib
          - g++-multilib
